with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  cifrato/internal/domain/repository:
    interfaces:
      TaxRuleRepository:
      CalculationRepository:
      ReferenceDataRepository:
      LineClassifier:
      ClassificationCacheRepository:
      InvoiceParser:
      InvoiceRepository:
  cifrato/internal/application/ports/in:
    interfaces:
      ClassifyInvoiceLines:
      CalculateWithholdings:
