// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "cifrato/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockClassifyInvoiceLines is an autogenerated mock type for the ClassifyInvoiceLines type
type MockClassifyInvoiceLines struct {
	mock.Mock
}

type MockClassifyInvoiceLines_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClassifyInvoiceLines) EXPECT() *MockClassifyInvoiceLines_Expecter {
	return &MockClassifyInvoiceLines_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, inv
func (_m *MockClassifyInvoiceLines) Execute(ctx context.Context, inv *entity.Invoice) error {
	ret := _m.Called(ctx, inv)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Invoice) error); ok {
		r0 = rf(ctx, inv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClassifyInvoiceLines_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockClassifyInvoiceLines_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - inv *entity.Invoice
func (_e *MockClassifyInvoiceLines_Expecter) Execute(ctx interface{}, inv interface{}) *MockClassifyInvoiceLines_Execute_Call {
	return &MockClassifyInvoiceLines_Execute_Call{Call: _e.mock.On("Execute", ctx, inv)}
}

func (_c *MockClassifyInvoiceLines_Execute_Call) Run(run func(ctx context.Context, inv *entity.Invoice)) *MockClassifyInvoiceLines_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Invoice))
	})
	return _c
}

func (_c *MockClassifyInvoiceLines_Execute_Call) Return(_a0 error) *MockClassifyInvoiceLines_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClassifyInvoiceLines_Execute_Call) RunAndReturn(run func(context.Context, *entity.Invoice) error) *MockClassifyInvoiceLines_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClassifyInvoiceLines creates a new instance of MockClassifyInvoiceLines. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClassifyInvoiceLines(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClassifyInvoiceLines {
	mock := &MockClassifyInvoiceLines{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
