// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "cifrato/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCalculateWithholdings is an autogenerated mock type for the CalculateWithholdings type
type MockCalculateWithholdings struct {
	mock.Mock
}

type MockCalculateWithholdings_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCalculateWithholdings) EXPECT() *MockCalculateWithholdings_Expecter {
	return &MockCalculateWithholdings_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, inv
func (_m *MockCalculateWithholdings) Execute(ctx context.Context, inv *entity.Invoice) ([]entity.Calculation, error) {
	ret := _m.Called(ctx, inv)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []entity.Calculation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Invoice) ([]entity.Calculation, error)); ok {
		return rf(ctx, inv)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Invoice) []entity.Calculation); ok {
		r0 = rf(ctx, inv)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Calculation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Invoice) error); ok {
		r1 = rf(ctx, inv)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCalculateWithholdings_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCalculateWithholdings_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - inv *entity.Invoice
func (_e *MockCalculateWithholdings_Expecter) Execute(ctx interface{}, inv interface{}) *MockCalculateWithholdings_Execute_Call {
	return &MockCalculateWithholdings_Execute_Call{Call: _e.mock.On("Execute", ctx, inv)}
}

func (_c *MockCalculateWithholdings_Execute_Call) Run(run func(ctx context.Context, inv *entity.Invoice)) *MockCalculateWithholdings_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Invoice))
	})
	return _c
}

func (_c *MockCalculateWithholdings_Execute_Call) Return(_a0 []entity.Calculation, _a1 error) *MockCalculateWithholdings_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCalculateWithholdings_Execute_Call) RunAndReturn(run func(context.Context, *entity.Invoice) ([]entity.Calculation, error)) *MockCalculateWithholdings_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCalculateWithholdings creates a new instance of MockCalculateWithholdings. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCalculateWithholdings(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCalculateWithholdings {
	mock := &MockCalculateWithholdings{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
