// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "cifrato/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCalculationRepository is an autogenerated mock type for the CalculationRepository type
type MockCalculationRepository struct {
	mock.Mock
}

type MockCalculationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCalculationRepository) EXPECT() *MockCalculationRepository_Expecter {
	return &MockCalculationRepository_Expecter{mock: &_m.Mock}
}

// ListByInvoice provides a mock function with given fields: ctx, invoiceID
func (_m *MockCalculationRepository) ListByInvoice(ctx context.Context, invoiceID uint) ([]entity.Calculation, error) {
	ret := _m.Called(ctx, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for ListByInvoice")
	}

	var r0 []entity.Calculation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entity.Calculation, error)); ok {
		return rf(ctx, invoiceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entity.Calculation); ok {
		r0 = rf(ctx, invoiceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Calculation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, invoiceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCalculationRepository_ListByInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByInvoice'
type MockCalculationRepository_ListByInvoice_Call struct {
	*mock.Call
}

// ListByInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID uint
func (_e *MockCalculationRepository_Expecter) ListByInvoice(ctx interface{}, invoiceID interface{}) *MockCalculationRepository_ListByInvoice_Call {
	return &MockCalculationRepository_ListByInvoice_Call{Call: _e.mock.On("ListByInvoice", ctx, invoiceID)}
}

func (_c *MockCalculationRepository_ListByInvoice_Call) Run(run func(ctx context.Context, invoiceID uint)) *MockCalculationRepository_ListByInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockCalculationRepository_ListByInvoice_Call) Return(_a0 []entity.Calculation, _a1 error) *MockCalculationRepository_ListByInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCalculationRepository_ListByInvoice_Call) RunAndReturn(run func(context.Context, uint) ([]entity.Calculation, error)) *MockCalculationRepository_ListByInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, calc
func (_m *MockCalculationRepository) Upsert(ctx context.Context, calc *entity.Calculation) error {
	ret := _m.Called(ctx, calc)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Calculation) error); ok {
		r0 = rf(ctx, calc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCalculationRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockCalculationRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - calc *entity.Calculation
func (_e *MockCalculationRepository_Expecter) Upsert(ctx interface{}, calc interface{}) *MockCalculationRepository_Upsert_Call {
	return &MockCalculationRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, calc)}
}

func (_c *MockCalculationRepository_Upsert_Call) Run(run func(ctx context.Context, calc *entity.Calculation)) *MockCalculationRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Calculation))
	})
	return _c
}

func (_c *MockCalculationRepository_Upsert_Call) Return(_a0 error) *MockCalculationRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCalculationRepository_Upsert_Call) RunAndReturn(run func(context.Context, *entity.Calculation) error) *MockCalculationRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCalculationRepository creates a new instance of MockCalculationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCalculationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCalculationRepository {
	mock := &MockCalculationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
