// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "cifrato/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockInvoiceParser is an autogenerated mock type for the InvoiceParser type
type MockInvoiceParser struct {
	mock.Mock
}

type MockInvoiceParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvoiceParser) EXPECT() *MockInvoiceParser_Expecter {
	return &MockInvoiceParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: xmlData
func (_m *MockInvoiceParser) Parse(xmlData []byte) (*entity.Invoice, error) {
	ret := _m.Called(xmlData)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *entity.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (*entity.Invoice, error)); ok {
		return rf(xmlData)
	}
	if rf, ok := ret.Get(0).(func([]byte) *entity.Invoice); ok {
		r0 = rf(xmlData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(xmlData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInvoiceParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockInvoiceParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - xmlData []byte
func (_e *MockInvoiceParser_Expecter) Parse(xmlData interface{}) *MockInvoiceParser_Parse_Call {
	return &MockInvoiceParser_Parse_Call{Call: _e.mock.On("Parse", xmlData)}
}

func (_c *MockInvoiceParser_Parse_Call) Run(run func(xmlData []byte)) *MockInvoiceParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockInvoiceParser_Parse_Call) Return(_a0 *entity.Invoice, _a1 error) *MockInvoiceParser_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInvoiceParser_Parse_Call) RunAndReturn(run func([]byte) (*entity.Invoice, error)) *MockInvoiceParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInvoiceParser creates a new instance of MockInvoiceParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvoiceParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvoiceParser {
	mock := &MockInvoiceParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
