// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "cifrato/internal/domain/entity"
	enums "cifrato/internal/domain/enums"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTaxRuleRepository is an autogenerated mock type for the TaxRuleRepository type
type MockTaxRuleRepository struct {
	mock.Mock
}

type MockTaxRuleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaxRuleRepository) EXPECT() *MockTaxRuleRepository_Expecter {
	return &MockTaxRuleRepository_Expecter{mock: &_m.Mock}
}

// FindApplicable provides a mock function with given fields: ctx, taxType, conceptID, cityID, at
func (_m *MockTaxRuleRepository) FindApplicable(ctx context.Context, taxType enums.TaxType, conceptID uint, cityID *uint, at time.Time) (*entity.TaxRule, error) {
	ret := _m.Called(ctx, taxType, conceptID, cityID, at)

	if len(ret) == 0 {
		panic("no return value specified for FindApplicable")
	}

	var r0 *entity.TaxRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, enums.TaxType, uint, *uint, time.Time) (*entity.TaxRule, error)); ok {
		return rf(ctx, taxType, conceptID, cityID, at)
	}
	if rf, ok := ret.Get(0).(func(context.Context, enums.TaxType, uint, *uint, time.Time) *entity.TaxRule); ok {
		r0 = rf(ctx, taxType, conceptID, cityID, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaxRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, enums.TaxType, uint, *uint, time.Time) error); ok {
		r1 = rf(ctx, taxType, conceptID, cityID, at)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaxRuleRepository_FindApplicable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindApplicable'
type MockTaxRuleRepository_FindApplicable_Call struct {
	*mock.Call
}

// FindApplicable is a helper method to define mock.On call
//   - ctx context.Context
//   - taxType enums.TaxType
//   - conceptID uint
//   - cityID *uint
//   - at time.Time
func (_e *MockTaxRuleRepository_Expecter) FindApplicable(ctx interface{}, taxType interface{}, conceptID interface{}, cityID interface{}, at interface{}) *MockTaxRuleRepository_FindApplicable_Call {
	return &MockTaxRuleRepository_FindApplicable_Call{Call: _e.mock.On("FindApplicable", ctx, taxType, conceptID, cityID, at)}
}

func (_c *MockTaxRuleRepository_FindApplicable_Call) Run(run func(ctx context.Context, taxType enums.TaxType, conceptID uint, cityID *uint, at time.Time)) *MockTaxRuleRepository_FindApplicable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(enums.TaxType), args[2].(uint), args[3].(*uint), args[4].(time.Time))
	})
	return _c
}

func (_c *MockTaxRuleRepository_FindApplicable_Call) Return(_a0 *entity.TaxRule, _a1 error) *MockTaxRuleRepository_FindApplicable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaxRuleRepository_FindApplicable_Call) RunAndReturn(run func(context.Context, enums.TaxType, uint, *uint, time.Time) (*entity.TaxRule, error)) *MockTaxRuleRepository_FindApplicable_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTaxType provides a mock function with given fields: ctx, taxType
func (_m *MockTaxRuleRepository) ListByTaxType(ctx context.Context, taxType enums.TaxType) ([]entity.TaxRule, error) {
	ret := _m.Called(ctx, taxType)

	if len(ret) == 0 {
		panic("no return value specified for ListByTaxType")
	}

	var r0 []entity.TaxRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, enums.TaxType) ([]entity.TaxRule, error)); ok {
		return rf(ctx, taxType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, enums.TaxType) []entity.TaxRule); ok {
		r0 = rf(ctx, taxType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TaxRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, enums.TaxType) error); ok {
		r1 = rf(ctx, taxType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaxRuleRepository_ListByTaxType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTaxType'
type MockTaxRuleRepository_ListByTaxType_Call struct {
	*mock.Call
}

// ListByTaxType is a helper method to define mock.On call
//   - ctx context.Context
//   - taxType enums.TaxType
func (_e *MockTaxRuleRepository_Expecter) ListByTaxType(ctx interface{}, taxType interface{}) *MockTaxRuleRepository_ListByTaxType_Call {
	return &MockTaxRuleRepository_ListByTaxType_Call{Call: _e.mock.On("ListByTaxType", ctx, taxType)}
}

func (_c *MockTaxRuleRepository_ListByTaxType_Call) Run(run func(ctx context.Context, taxType enums.TaxType)) *MockTaxRuleRepository_ListByTaxType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(enums.TaxType))
	})
	return _c
}

func (_c *MockTaxRuleRepository_ListByTaxType_Call) Return(_a0 []entity.TaxRule, _a1 error) *MockTaxRuleRepository_ListByTaxType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaxRuleRepository_ListByTaxType_Call) RunAndReturn(run func(context.Context, enums.TaxType) ([]entity.TaxRule, error)) *MockTaxRuleRepository_ListByTaxType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaxRuleRepository creates a new instance of MockTaxRuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaxRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaxRuleRepository {
	mock := &MockTaxRuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
