// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "cifrato/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockInvoiceRepository is an autogenerated mock type for the InvoiceRepository type
type MockInvoiceRepository struct {
	mock.Mock
}

type MockInvoiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvoiceRepository) EXPECT() *MockInvoiceRepository_Expecter {
	return &MockInvoiceRepository_Expecter{mock: &_m.Mock}
}

// ExistsByCUFE provides a mock function with given fields: ctx, cufe
func (_m *MockInvoiceRepository) ExistsByCUFE(ctx context.Context, cufe string) (bool, error) {
	ret := _m.Called(ctx, cufe)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByCUFE")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, cufe)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, cufe)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cufe)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInvoiceRepository_ExistsByCUFE_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByCUFE'
type MockInvoiceRepository_ExistsByCUFE_Call struct {
	*mock.Call
}

// ExistsByCUFE is a helper method to define mock.On call
//   - ctx context.Context
//   - cufe string
func (_e *MockInvoiceRepository_Expecter) ExistsByCUFE(ctx interface{}, cufe interface{}) *MockInvoiceRepository_ExistsByCUFE_Call {
	return &MockInvoiceRepository_ExistsByCUFE_Call{Call: _e.mock.On("ExistsByCUFE", ctx, cufe)}
}

func (_c *MockInvoiceRepository_ExistsByCUFE_Call) Run(run func(ctx context.Context, cufe string)) *MockInvoiceRepository_ExistsByCUFE_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInvoiceRepository_ExistsByCUFE_Call) Return(_a0 bool, _a1 error) *MockInvoiceRepository_ExistsByCUFE_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInvoiceRepository_ExistsByCUFE_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockInvoiceRepository_ExistsByCUFE_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCUFE provides a mock function with given fields: ctx, cufe
func (_m *MockInvoiceRepository) FindByCUFE(ctx context.Context, cufe string) (*entity.Invoice, error) {
	ret := _m.Called(ctx, cufe)

	if len(ret) == 0 {
		panic("no return value specified for FindByCUFE")
	}

	var r0 *entity.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Invoice, error)); ok {
		return rf(ctx, cufe)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Invoice); ok {
		r0 = rf(ctx, cufe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cufe)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInvoiceRepository_FindByCUFE_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCUFE'
type MockInvoiceRepository_FindByCUFE_Call struct {
	*mock.Call
}

// FindByCUFE is a helper method to define mock.On call
//   - ctx context.Context
//   - cufe string
func (_e *MockInvoiceRepository_Expecter) FindByCUFE(ctx interface{}, cufe interface{}) *MockInvoiceRepository_FindByCUFE_Call {
	return &MockInvoiceRepository_FindByCUFE_Call{Call: _e.mock.On("FindByCUFE", ctx, cufe)}
}

func (_c *MockInvoiceRepository_FindByCUFE_Call) Run(run func(ctx context.Context, cufe string)) *MockInvoiceRepository_FindByCUFE_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInvoiceRepository_FindByCUFE_Call) Return(_a0 *entity.Invoice, _a1 error) *MockInvoiceRepository_FindByCUFE_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInvoiceRepository_FindByCUFE_Call) RunAndReturn(run func(context.Context, string) (*entity.Invoice, error)) *MockInvoiceRepository_FindByCUFE_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, inv
func (_m *MockInvoiceRepository) Save(ctx context.Context, inv *entity.Invoice) error {
	ret := _m.Called(ctx, inv)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Invoice) error); ok {
		r0 = rf(ctx, inv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInvoiceRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockInvoiceRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - inv *entity.Invoice
func (_e *MockInvoiceRepository_Expecter) Save(ctx interface{}, inv interface{}) *MockInvoiceRepository_Save_Call {
	return &MockInvoiceRepository_Save_Call{Call: _e.mock.On("Save", ctx, inv)}
}

func (_c *MockInvoiceRepository_Save_Call) Run(run func(ctx context.Context, inv *entity.Invoice)) *MockInvoiceRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Invoice))
	})
	return _c
}

func (_c *MockInvoiceRepository_Save_Call) Return(_a0 error) *MockInvoiceRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInvoiceRepository_Save_Call) RunAndReturn(run func(context.Context, *entity.Invoice) error) *MockInvoiceRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInvoiceRepository creates a new instance of MockInvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
