// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "cifrato/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockClassificationCacheRepository is an autogenerated mock type for the ClassificationCacheRepository type
type MockClassificationCacheRepository struct {
	mock.Mock
}

type MockClassificationCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClassificationCacheRepository) EXPECT() *MockClassificationCacheRepository_Expecter {
	return &MockClassificationCacheRepository_Expecter{mock: &_m.Mock}
}

// FindByDescription provides a mock function with given fields: ctx, descriptionNormalized
func (_m *MockClassificationCacheRepository) FindByDescription(ctx context.Context, descriptionNormalized string) (*entity.ClassificationCacheEntry, error) {
	ret := _m.Called(ctx, descriptionNormalized)

	if len(ret) == 0 {
		panic("no return value specified for FindByDescription")
	}

	var r0 *entity.ClassificationCacheEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.ClassificationCacheEntry, error)); ok {
		return rf(ctx, descriptionNormalized)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.ClassificationCacheEntry); ok {
		r0 = rf(ctx, descriptionNormalized)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ClassificationCacheEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, descriptionNormalized)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClassificationCacheRepository_FindByDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDescription'
type MockClassificationCacheRepository_FindByDescription_Call struct {
	*mock.Call
}

// FindByDescription is a helper method to define mock.On call
//   - ctx context.Context
//   - descriptionNormalized string
func (_e *MockClassificationCacheRepository_Expecter) FindByDescription(ctx interface{}, descriptionNormalized interface{}) *MockClassificationCacheRepository_FindByDescription_Call {
	return &MockClassificationCacheRepository_FindByDescription_Call{Call: _e.mock.On("FindByDescription", ctx, descriptionNormalized)}
}

func (_c *MockClassificationCacheRepository_FindByDescription_Call) Run(run func(ctx context.Context, descriptionNormalized string)) *MockClassificationCacheRepository_FindByDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClassificationCacheRepository_FindByDescription_Call) Return(_a0 *entity.ClassificationCacheEntry, _a1 error) *MockClassificationCacheRepository_FindByDescription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClassificationCacheRepository_FindByDescription_Call) RunAndReturn(run func(context.Context, string) (*entity.ClassificationCacheEntry, error)) *MockClassificationCacheRepository_FindByDescription_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIssuerAndSKU provides a mock function with given fields: ctx, issuerNIT, sku
func (_m *MockClassificationCacheRepository) FindByIssuerAndSKU(ctx context.Context, issuerNIT string, sku string) (*entity.ClassificationCacheEntry, error) {
	ret := _m.Called(ctx, issuerNIT, sku)

	if len(ret) == 0 {
		panic("no return value specified for FindByIssuerAndSKU")
	}

	var r0 *entity.ClassificationCacheEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.ClassificationCacheEntry, error)); ok {
		return rf(ctx, issuerNIT, sku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.ClassificationCacheEntry); ok {
		r0 = rf(ctx, issuerNIT, sku)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ClassificationCacheEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, issuerNIT, sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClassificationCacheRepository_FindByIssuerAndSKU_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIssuerAndSKU'
type MockClassificationCacheRepository_FindByIssuerAndSKU_Call struct {
	*mock.Call
}

// FindByIssuerAndSKU is a helper method to define mock.On call
//   - ctx context.Context
//   - issuerNIT string
//   - sku string
func (_e *MockClassificationCacheRepository_Expecter) FindByIssuerAndSKU(ctx interface{}, issuerNIT interface{}, sku interface{}) *MockClassificationCacheRepository_FindByIssuerAndSKU_Call {
	return &MockClassificationCacheRepository_FindByIssuerAndSKU_Call{Call: _e.mock.On("FindByIssuerAndSKU", ctx, issuerNIT, sku)}
}

func (_c *MockClassificationCacheRepository_FindByIssuerAndSKU_Call) Run(run func(ctx context.Context, issuerNIT string, sku string)) *MockClassificationCacheRepository_FindByIssuerAndSKU_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClassificationCacheRepository_FindByIssuerAndSKU_Call) Return(_a0 *entity.ClassificationCacheEntry, _a1 error) *MockClassificationCacheRepository_FindByIssuerAndSKU_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClassificationCacheRepository_FindByIssuerAndSKU_Call) RunAndReturn(run func(context.Context, string, string) (*entity.ClassificationCacheEntry, error)) *MockClassificationCacheRepository_FindByIssuerAndSKU_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, entry
func (_m *MockClassificationCacheRepository) Save(ctx context.Context, entry *entity.ClassificationCacheEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ClassificationCacheEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClassificationCacheRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockClassificationCacheRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *entity.ClassificationCacheEntry
func (_e *MockClassificationCacheRepository_Expecter) Save(ctx interface{}, entry interface{}) *MockClassificationCacheRepository_Save_Call {
	return &MockClassificationCacheRepository_Save_Call{Call: _e.mock.On("Save", ctx, entry)}
}

func (_c *MockClassificationCacheRepository_Save_Call) Run(run func(ctx context.Context, entry *entity.ClassificationCacheEntry)) *MockClassificationCacheRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ClassificationCacheEntry))
	})
	return _c
}

func (_c *MockClassificationCacheRepository_Save_Call) Return(_a0 error) *MockClassificationCacheRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClassificationCacheRepository_Save_Call) RunAndReturn(run func(context.Context, *entity.ClassificationCacheEntry) error) *MockClassificationCacheRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClassificationCacheRepository creates a new instance of MockClassificationCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClassificationCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClassificationCacheRepository {
	mock := &MockClassificationCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
