// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "cifrato/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockReferenceDataRepository is an autogenerated mock type for the ReferenceDataRepository type
type MockReferenceDataRepository struct {
	mock.Mock
}

type MockReferenceDataRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReferenceDataRepository) EXPECT() *MockReferenceDataRepository_Expecter {
	return &MockReferenceDataRepository_Expecter{mock: &_m.Mock}
}

// FindCityByName provides a mock function with given fields: ctx, name
func (_m *MockReferenceDataRepository) FindCityByName(ctx context.Context, name string) (*entity.City, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindCityByName")
	}

	var r0 *entity.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.City, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.City); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReferenceDataRepository_FindCityByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCityByName'
type MockReferenceDataRepository_FindCityByName_Call struct {
	*mock.Call
}

// FindCityByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockReferenceDataRepository_Expecter) FindCityByName(ctx interface{}, name interface{}) *MockReferenceDataRepository_FindCityByName_Call {
	return &MockReferenceDataRepository_FindCityByName_Call{Call: _e.mock.On("FindCityByName", ctx, name)}
}

func (_c *MockReferenceDataRepository_FindCityByName_Call) Run(run func(ctx context.Context, name string)) *MockReferenceDataRepository_FindCityByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReferenceDataRepository_FindCityByName_Call) Return(_a0 *entity.City, _a1 error) *MockReferenceDataRepository_FindCityByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReferenceDataRepository_FindCityByName_Call) RunAndReturn(run func(context.Context, string) (*entity.City, error)) *MockReferenceDataRepository_FindCityByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindConceptByCode provides a mock function with given fields: ctx, code
func (_m *MockReferenceDataRepository) FindConceptByCode(ctx context.Context, code string) (*entity.Concept, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindConceptByCode")
	}

	var r0 *entity.Concept
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Concept, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Concept); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Concept)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReferenceDataRepository_FindConceptByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindConceptByCode'
type MockReferenceDataRepository_FindConceptByCode_Call struct {
	*mock.Call
}

// FindConceptByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockReferenceDataRepository_Expecter) FindConceptByCode(ctx interface{}, code interface{}) *MockReferenceDataRepository_FindConceptByCode_Call {
	return &MockReferenceDataRepository_FindConceptByCode_Call{Call: _e.mock.On("FindConceptByCode", ctx, code)}
}

func (_c *MockReferenceDataRepository_FindConceptByCode_Call) Run(run func(ctx context.Context, code string)) *MockReferenceDataRepository_FindConceptByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReferenceDataRepository_FindConceptByCode_Call) Return(_a0 *entity.Concept, _a1 error) *MockReferenceDataRepository_FindConceptByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReferenceDataRepository_FindConceptByCode_Call) RunAndReturn(run func(context.Context, string) (*entity.Concept, error)) *MockReferenceDataRepository_FindConceptByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindUVTValue provides a mock function with given fields: ctx, at
func (_m *MockReferenceDataRepository) FindUVTValue(ctx context.Context, at time.Time) (*entity.UVTValue, error) {
	ret := _m.Called(ctx, at)

	if len(ret) == 0 {
		panic("no return value specified for FindUVTValue")
	}

	var r0 *entity.UVTValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (*entity.UVTValue, error)); ok {
		return rf(ctx, at)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) *entity.UVTValue); ok {
		r0 = rf(ctx, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UVTValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, at)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReferenceDataRepository_FindUVTValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUVTValue'
type MockReferenceDataRepository_FindUVTValue_Call struct {
	*mock.Call
}

// FindUVTValue is a helper method to define mock.On call
//   - ctx context.Context
//   - at time.Time
func (_e *MockReferenceDataRepository_Expecter) FindUVTValue(ctx interface{}, at interface{}) *MockReferenceDataRepository_FindUVTValue_Call {
	return &MockReferenceDataRepository_FindUVTValue_Call{Call: _e.mock.On("FindUVTValue", ctx, at)}
}

func (_c *MockReferenceDataRepository_FindUVTValue_Call) Run(run func(ctx context.Context, at time.Time)) *MockReferenceDataRepository_FindUVTValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockReferenceDataRepository_FindUVTValue_Call) Return(_a0 *entity.UVTValue, _a1 error) *MockReferenceDataRepository_FindUVTValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReferenceDataRepository_FindUVTValue_Call) RunAndReturn(run func(context.Context, time.Time) (*entity.UVTValue, error)) *MockReferenceDataRepository_FindUVTValue_Call {
	_c.Call.Return(run)
	return _c
}

// ListConcepts provides a mock function with given fields: ctx
func (_m *MockReferenceDataRepository) ListConcepts(ctx context.Context) ([]entity.Concept, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListConcepts")
	}

	var r0 []entity.Concept
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Concept, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Concept); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Concept)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReferenceDataRepository_ListConcepts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConcepts'
type MockReferenceDataRepository_ListConcepts_Call struct {
	*mock.Call
}

// ListConcepts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReferenceDataRepository_Expecter) ListConcepts(ctx interface{}) *MockReferenceDataRepository_ListConcepts_Call {
	return &MockReferenceDataRepository_ListConcepts_Call{Call: _e.mock.On("ListConcepts", ctx)}
}

func (_c *MockReferenceDataRepository_ListConcepts_Call) Run(run func(ctx context.Context)) *MockReferenceDataRepository_ListConcepts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReferenceDataRepository_ListConcepts_Call) Return(_a0 []entity.Concept, _a1 error) *MockReferenceDataRepository_ListConcepts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReferenceDataRepository_ListConcepts_Call) RunAndReturn(run func(context.Context) ([]entity.Concept, error)) *MockReferenceDataRepository_ListConcepts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReferenceDataRepository creates a new instance of MockReferenceDataRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReferenceDataRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReferenceDataRepository {
	mock := &MockReferenceDataRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
