// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "cifrato/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLineClassifier is an autogenerated mock type for the LineClassifier type
type MockLineClassifier struct {
	mock.Mock
}

type MockLineClassifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLineClassifier) EXPECT() *MockLineClassifier_Expecter {
	return &MockLineClassifier_Expecter{mock: &_m.Mock}
}

// Classify provides a mock function with given fields: ctx, description
func (_m *MockLineClassifier) Classify(ctx context.Context, description string) (*entity.LineClassification, error) {
	ret := _m.Called(ctx, description)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 *entity.LineClassification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.LineClassification, error)); ok {
		return rf(ctx, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.LineClassification); ok {
		r0 = rf(ctx, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LineClassification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLineClassifier_Classify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Classify'
type MockLineClassifier_Classify_Call struct {
	*mock.Call
}

// Classify is a helper method to define mock.On call
//   - ctx context.Context
//   - description string
func (_e *MockLineClassifier_Expecter) Classify(ctx interface{}, description interface{}) *MockLineClassifier_Classify_Call {
	return &MockLineClassifier_Classify_Call{Call: _e.mock.On("Classify", ctx, description)}
}

func (_c *MockLineClassifier_Classify_Call) Run(run func(ctx context.Context, description string)) *MockLineClassifier_Classify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLineClassifier_Classify_Call) Return(_a0 *entity.LineClassification, _a1 error) *MockLineClassifier_Classify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLineClassifier_Classify_Call) RunAndReturn(run func(context.Context, string) (*entity.LineClassification, error)) *MockLineClassifier_Classify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLineClassifier creates a new instance of MockLineClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLineClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLineClassifier {
	mock := &MockLineClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
